#!/usr/bin/env python
#-*- coding: cp866 -*-

import sys
import time

import scrollphat
import Adafruit_VCNL40xx

# as this starts at boot, we want to give some time for cool animation that plays for 5 seconds from another file
time.sleep(0)
scrollphat.set_brightness(5)

# Create a VCNL4010 instance.
vcnl = Adafruit_VCNL40xx.VCNL4010()

# Add exception from proximity sensor. If sensor triggers, newsreader switches to another news source
def prox():
  # number based on experiments: approx 2220 and less is shown when sensor doesn't see anything
  dist = 2235
  while True:
    # Read proximity.
    proximity = vcnl.read_proximity()
    if proximity > dist:
      print('Proximity={0}'.format(proximity))
      time.sleep(0.5)
      return True
    return False


# define databases to read the news from
db_1 = '/home/pi/Pimoroni/scrollphat/feed_1.db'
db_2 = '/home/pi/Pimoroni/scrollphat/feed_2.db'

def news(db):
        f = open(db)
        print iter(f)
        for msg in iter(f):
#               this is to ensure no non-ASCII stuff goes through, otherwise program shuts down
                msg = msg.decode('utf-8', errors='ignore').encode('utf-8')
#               check if any text exists on this line exists, otherwise move to next line
                if '|' in msg:
#                       clear buffer of previous message
                        msg = msg.decode('utf-8')
                        scrollphat.clear()
#                       split message in 2 pieces to get rid of timestamp
                        first_p,second_p=msg.split("|")
#                       print only first part before delimeter
                        scrollphat.write_string('       '+ first_p)
                        for i in range(0, scrollphat.buffer_len()):
                                scrollphat.scroll()
                                time.sleep(0.035)
                                if prox():
                                        f.close()
                                        return
                else: print('no data to show, jumping to next line')

        else:   
                f.close()
                f = open(db_1)
                print iter(f)

while True:
        try:
                news(db_1)
                news(db_2)
        except KeyboardInterrupt:
                scrollphat.clear()
#               f.close()
                sys.exit(-1)


